version: "3.1"

services:
  db:
    image: postgres:12.3
    restart: always
    ports:
      - "4001:5432"
    environment:
      POSTGRES_DB: telescope
      POSTGRES_PASSWORD: password
      POSTGRES_USER: telescope
